[package]
name = "halley-lift"
version = "0.3.0"
edition = "2024"
description = "Search and action launcher for the Halley Wayland compositor"
authors = ["Dustin Pilgrim <dustin.pilgrim1997@gmail.com>"]
license = "GPL-3.0-only"
readme = "README.md"
repository = "https://github.com/saltnpepper97/halley-lift"
homepage = "https://github.com/saltnpepper97/halley"
keywords = ["wayland", "launcher", "halley"]
categories = ["gui"]

[dependencies]
halley-ui = { version = "=0.1.2", features = ["accessibility-unix"] }
calloop = "0.14.4"
calloop-wayland-source = "0.4.1"
freedesktop-icons = "0.4.0"
halley-api = "0.4.0"
rune-cfg = "0.7.1"
smithay-client-toolkit = "0.20.0"
wayland-client = "0.31.14"

[[bin]]
name = "halley-lift"
path = "src/main.rs"
